name: on-push

on:

  push:
    branches:
      - main

  workflow_dispatch:
    inputs:
      TRIGGER_ALL:
        type: boolean
        default: true
        description: "Bump and release all components?"

permissions:
  contents: write
  pull-requests: write
  id-token: write

defaults:
  run:
    shell: bash

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

jobs:

  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      changed-component-types: ${{ steps.components-changed.outputs.changed-component-types }}
      changed-components-by-type: ${{ steps.components-changed.outputs.changed-components-by-type }}
    steps:
      -
        uses: actions/checkout@v6
      -
        name: Detect changed components
        id: components-changed
        uses: slingshot-pipelines/action-components-changed@v1
        with:
          all: ${{ github.event_name == 'workflow_dispatch' && inputs.TRIGGER_ALL }}

  terragrunt-infra:
    needs:
      - detect-changes
    if: ${{ contains(needs.detect-changes.outputs.changed-component-types, '"terragrunt-infra"') }}
    uses: slingshot-pipelines/workflows/.github/workflows/deploy-sequence-start.yml@deploy-sequence-start/v0
    strategy:
      matrix:
        COMPONENT: ${{ fromJSON(needs.detect-changes.outputs.changed-components-by-type).terragrunt-infra }}
    with:
      COMPONENT: ${{ matrix.COMPONENT }}
    secrets: inherit

  s3-website:
    needs:
      - detect-changes
    if: ${{ contains(needs.detect-changes.outputs.changed-component-types, '"s3-website"') }}
    uses: slingshot-pipelines/workflows/.github/workflows/deploy-sequence-start.yml@deploy-sequence-start/v0
    strategy:
      matrix:
        COMPONENT: ${{ fromJSON(needs.detect-changes.outputs.changed-components-by-type).s3-website }}
    with:
      COMPONENT: ${{ matrix.COMPONENT }}
    secrets: inherit
